name: TreexBuyer
version: ${project.version}
main: org.jetby.treexBuyer.TreexBuyer
api-version: '1.20'
load: POSTWORLD
authors: [ MrJetby ]
website: https://jetby.org
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - ProtocolLib
  - Libb
commands:
  treexbuyer:
    aliases:
      - tb
      - tbuyer